# Generated by Django 4.2.23 on 2025-06-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0069_softwareimagefile_external_integration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cable',
            unique_together=set(),
        ),
    ]
