# Generated by Django 4.2.23 on 2025-06-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0069_softwareimagefile_external_integration"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cable",
            constraint=models.UniqueConstraint(
                condition=models.Q(("termination_a_id__lt", models.F("termination_b_id"))),
                fields=("termination_a_id", "termination_b_id"),
                name="cable_uniqueness_a_lt_b",
            ),
        ),
        migrations.AddConstraint(
            model_name="cable",
            constraint=models.UniqueConstraint(
                condition=models.Q(("termination_b_id__lt", models.F("termination_a_id"))),
                fields=("termination_a_id", "termination_b_id"),
                name="cable_uniqueness_b_lt_a",
            ),
        ),
    ]
