# Generated by Django 4.2.23 on 2025-06-19 14:50
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations

# https://docs.djangoproject.com/en/5.2/ref/contrib/postgres/constraints/#:~:text=ExclusionConstraint


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0069_softwareimagefile_external_integration"),
    ]

    operations = [
        BtreeGistExtension(),
    ]
