# Generated manually for final CableTermination structure

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0086_link_cabletermination_ptr_fields"),
    ]

    operations = [
        # Remove old fields first (including old id primary keys) before setting new primary keys
        migrations.RemoveField(model_name="consoleport", name="cable"),
        migrations.RemoveField(model_name="consoleport", name="_cable_peer_id"),
        migrations.RemoveField(model_name="consoleport", name="_cable_peer_type"),
        migrations.RemoveField(model_name="consoleport", name="created"),
        migrations.RemoveField(model_name="consoleport", name="last_updated"),
        migrations.RemoveField(model_name="consoleport", name="_custom_field_data"),
        migrations.RemoveField(model_name="consoleport", name="tags"),
        migrations.RemoveField(model_name="consoleport", name="id"),
        migrations.RemoveField(model_name="consoleserverport", name="cable"),
        migrations.RemoveField(model_name="consoleserverport", name="_cable_peer_id"),
        migrations.RemoveField(model_name="consoleserverport", name="_cable_peer_type"),
        migrations.RemoveField(model_name="consoleserverport", name="created"),
        migrations.RemoveField(model_name="consoleserverport", name="last_updated"),
        migrations.RemoveField(model_name="consoleserverport", name="_custom_field_data"),
        migrations.RemoveField(model_name="consoleserverport", name="tags"),
        migrations.RemoveField(model_name="consoleserverport", name="id"),
        migrations.RemoveField(model_name="powerport", name="cable"),
        migrations.RemoveField(model_name="powerport", name="_cable_peer_id"),
        migrations.RemoveField(model_name="powerport", name="_cable_peer_type"),
        migrations.RemoveField(model_name="powerport", name="created"),
        migrations.RemoveField(model_name="powerport", name="last_updated"),
        migrations.RemoveField(model_name="powerport", name="_custom_field_data"),
        migrations.RemoveField(model_name="powerport", name="tags"),
        migrations.RemoveField(model_name="powerport", name="id"),
        migrations.RemoveField(model_name="poweroutlet", name="cable"),
        migrations.RemoveField(model_name="poweroutlet", name="_cable_peer_id"),
        migrations.RemoveField(model_name="poweroutlet", name="_cable_peer_type"),
        migrations.RemoveField(model_name="poweroutlet", name="created"),
        migrations.RemoveField(model_name="poweroutlet", name="last_updated"),
        migrations.RemoveField(model_name="poweroutlet", name="_custom_field_data"),
        migrations.RemoveField(model_name="poweroutlet", name="tags"),
        migrations.RemoveField(model_name="poweroutlet", name="id"),
        migrations.RemoveField(model_name="interface", name="cable"),
        migrations.RemoveField(model_name="interface", name="_cable_peer_id"),
        migrations.RemoveField(model_name="interface", name="_cable_peer_type"),
        migrations.RemoveField(model_name="interface", name="created"),
        migrations.RemoveField(model_name="interface", name="last_updated"),
        migrations.RemoveField(model_name="interface", name="_custom_field_data"),
        migrations.RemoveField(model_name="interface", name="tags"),
        migrations.RemoveField(model_name="interface", name="id"),
        migrations.RemoveField(model_name="frontport", name="cable"),
        migrations.RemoveField(model_name="frontport", name="_cable_peer_id"),
        migrations.RemoveField(model_name="frontport", name="_cable_peer_type"),
        migrations.RemoveField(model_name="frontport", name="created"),
        migrations.RemoveField(model_name="frontport", name="last_updated"),
        migrations.RemoveField(model_name="frontport", name="_custom_field_data"),
        migrations.RemoveField(model_name="frontport", name="tags"),
        migrations.RemoveField(model_name="frontport", name="id"),
        migrations.RemoveField(model_name="rearport", name="cable"),
        migrations.RemoveField(model_name="rearport", name="_cable_peer_id"),
        migrations.RemoveField(model_name="rearport", name="_cable_peer_type"),
        migrations.RemoveField(model_name="rearport", name="created"),
        migrations.RemoveField(model_name="rearport", name="last_updated"),
        migrations.RemoveField(model_name="rearport", name="_custom_field_data"),
        migrations.RemoveField(model_name="rearport", name="tags"),
        migrations.RemoveField(model_name="rearport", name="id"),
        migrations.RemoveField(model_name="powerfeed", name="cable"),
        migrations.RemoveField(model_name="powerfeed", name="_cable_peer_id"),
        migrations.RemoveField(model_name="powerfeed", name="_cable_peer_type"),
        migrations.RemoveField(model_name="powerfeed", name="created"),
        migrations.RemoveField(model_name="powerfeed", name="last_updated"),
        migrations.RemoveField(model_name="powerfeed", name="_custom_field_data"),
        migrations.RemoveField(model_name="powerfeed", name="tags"),
        migrations.RemoveField(model_name="powerfeed", name="id"),
        # Now make cabletermination_ptr non-nullable and set as primary key for each child model
        migrations.AlterField(
            model_name="consoleport",
            name="cabletermination_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="dcim.cabletermination",
            ),
        ),
        migrations.AlterField(
            model_name="consoleserverport",
            name="cabletermination_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="dcim.cabletermination",
            ),
        ),
        migrations.AlterField(
            model_name="powerport",
            name="cabletermination_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="dcim.cabletermination",
            ),
        ),
        migrations.AlterField(
            model_name="poweroutlet",
            name="cabletermination_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="dcim.cabletermination",
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="cabletermination_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="dcim.cabletermination",
            ),
        ),
        migrations.AlterField(
            model_name="frontport",
            name="cabletermination_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="dcim.cabletermination",
            ),
        ),
        migrations.AlterField(
            model_name="rearport",
            name="cabletermination_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="dcim.cabletermination",
            ),
        ),
        migrations.AlterField(
            model_name="powerfeed",
            name="cabletermination_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="dcim.cabletermination",
            ),
        ),
    ]
