# Generated by Django 4.2.27 on 2026-02-05 20:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0087_finalize_cabletermination_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableEnd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cable_side', models.CharField(max_length=1)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['cable', 'cable_side', 'position'],
            },
        ),
        migrations.AlterModelOptions(
            name='cabletermination',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consoleport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consoleserverport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='poweroutlet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='powerport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rearport',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='consoleport',
            name='dcim_consoleport_device_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='consoleport',
            name='dcim_consoleport_module_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='consoleserverport',
            name='dcim_consoleserverport_device_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='consoleserverport',
            name='dcim_consoleserverport_module_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='poweroutlet',
            name='dcim_poweroutlet_device_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='poweroutlet',
            name='dcim_poweroutlet_module_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='powerport',
            name='dcim_powerport_device_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='powerport',
            name='dcim_powerport_module_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='rearport',
            name='dcim_rearport_device_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='rearport',
            name='dcim_rearport_module_name_unique',
        ),
        migrations.AlterField(
            model_name='cable',
            name='termination_a_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cable',
            name='termination_a_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'circuits'), ('model__in', ('circuittermination',))), models.Q(('app_label', 'dcim'), ('model__in', ('consoleport', 'consoleserverport', 'frontport', 'interface', 'powerfeed', 'poweroutlet', 'powerport', 'rearport'))), _connector='OR')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='cable',
            name='termination_b_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cable',
            name='termination_b_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'circuits'), ('model__in', ('circuittermination',))), models.Q(('app_label', 'dcim'), ('model__in', ('consoleport', 'consoleserverport', 'frontport', 'interface', 'powerfeed', 'poweroutlet', 'powerport', 'rearport'))), _connector='OR')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cableend',
            name='cable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_ends', to='dcim.cable'),
        ),
        migrations.AddField(
            model_name='cableend',
            name='cable_termination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_ends', to='dcim.cabletermination'),
        ),
        migrations.AlterUniqueTogether(
            name='cableend',
            unique_together={('cable', 'position', 'cable_side'), ('cable_termination',)},
        ),
    ]
