# Generated by Django 4.2.27 on 2026-02-12 13:42

from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.core.models.ordering


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0092_remove_cable_termination_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerfeed',
            name='_name',
            field=nautobot.core.models.fields.NaturalOrderingField('name', blank=True, db_index=True, max_length=255, naturalize_function=nautobot.core.models.ordering.naturalize),
        ),
        migrations.AddField(
            model_name='powerfeed',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='powerfeed',
            name='device',
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.device'),
        ),
        migrations.AddField(
            model_name='powerfeed',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='powerfeed',
            name='module',
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.module'),
        ),
    ]
