# Generated by Django 4.2.27 on 2026-02-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0096_remove_module_from_subclasses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consoleport',
            options={'ordering': ('device', 'module__id', '_name')},
        ),
        migrations.AlterModelOptions(
            name='consoleserverport',
            options={'ordering': ('device', 'module__id', '_name')},
        ),
        migrations.AlterModelOptions(
            name='poweroutlet',
            options={'ordering': ('device', 'module__id', '_name')},
        ),
        migrations.AlterModelOptions(
            name='powerport',
            options={'ordering': ('device', 'module__id', '_name')},
        ),
        migrations.AlterModelOptions(
            name='rearport',
            options={'ordering': ('device', 'module__id', '_name')},
        ),
        migrations.AddConstraint(
            model_name='consoleport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='dcim_consoleport_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='consoleserverport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='dcim_consoleserverport_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='frontport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='dcim_frontport_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='dcim_interface_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='poweroutlet',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='dcim_poweroutlet_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='powerport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='dcim_powerport_device_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='rearport',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='dcim_rearport_device_name_unique'),
        ),
    ]
