# Generated by Django 4.2.23 on 2025-08-20 15:10

from django.db import migrations, models
import django.db.models.deletion

from nautobot.extras.migrations.helpers.new_objectchange import make_funcs_for_model


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0022_circuittermination_cloud_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='circuits_providerchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='circuits.provider')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='ProviderNetworkObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='circuits_providernetworkchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='circuits.providernetwork')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='CircuitTypeObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='circuits_circuittypechangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='circuits.circuittype')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='CircuitTerminationObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='circuits_circuitterminationchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='circuits.circuittermination')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='CircuitObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='circuits_circuitchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='circuits.circuit')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.RunPython(*make_funcs_for_model('circuits', 'Provider')),
        migrations.RunPython(*make_funcs_for_model('circuits', 'ProviderNetwork')),
        migrations.RunPython(*make_funcs_for_model('circuits', 'CircuitType')),
        migrations.RunPython(*make_funcs_for_model('circuits', 'CircuitTermination')),
        migrations.RunPython(*make_funcs_for_model('circuits', 'Circuit')),
    ]
