# Generated by Django 4.2.23 on 2025-06-19 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("circuits", "0022_circuittermination_cloud_network"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="providernetwork",
            name="circuits_providernetwork_provider_name",
        ),
    ]
