# Generated by Django 4.2.23 on 2025-06-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circuits", "0023_remove_providernetwork_circuits_providernetwork_provider_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="circuittermination",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("cloud_network__isnull", True), ("location__isnull", False), ("provider_network__isnull", True)
                    ),
                    models.Q(
                        ("cloud_network__isnull", True), ("location__isnull", True), ("provider_network__isnull", False)
                    ),
                    models.Q(
                        ("cloud_network__isnull", False), ("location__isnull", True), ("provider_network__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="circuits_circuittermination_attachment_constraint",
                violation_error_message="A Circuit Termination can only attach to two elements between Location, Provider Network and Cloud Network",
            ),
        ),
    ]
