# Generated by Django 4.2.23 on 2025-08-20 15:10

from django.db import migrations

from nautobot.extras.migrations.helpers.new_objectchange import make_funcs_for_model


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0023_new_changelog'),
    ]

    operations = [
        migrations.RunPython(*make_funcs_for_model('circuits', 'Provider')),
        migrations.RunPython(*make_funcs_for_model('circuits', 'ProviderNetwork')),
        migrations.RunPython(*make_funcs_for_model('circuits', 'CircuitType')),
        migrations.RunPython(*make_funcs_for_model('circuits', 'CircuitTermination')),
        migrations.RunPython(*make_funcs_for_model('circuits', 'Circuit')),
    ]
