# Generated by Django 4.2.23 on 2025-06-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("circuits", "0023_remove_providernetwork_circuits_providernetwork_provider_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="circuittermination",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("cloud_network__isnull", False),
                    ("location__isnull", False),
                    ("provider_network__isnull", False),
                    _connector="XOR",
                ),
                name="circuits_circuittermination_attachment_constraint",
                violation_error_message="A Circuit Termination must attach to exactly one of: Location, Provider Network, or Cloud Network",
            ),
        ),
    ]
