# Generated by Django 4.2.23 on 2025-08-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0024_changelog_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuitobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='circuitterminationobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='circuittypeobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='providernetworkobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='providerobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
    ]
