# Generated by Django 4.2.23 on 2025-08-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0127_new_changelog"),
        ("users", "0010_user_default_saved_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectPermissionObjectChange",
            fields=[
                (
                    "changelog_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="users_objectpermissionchangelog",
                        serialize=False,
                        to="extras.objectchange",
                    ),
                ),
                ("target_uuid", models.UUIDField()),
                (
                    "fktarget",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="users.objectpermission",
                    ),
                ),
            ],
            bases=("extras.objectchange",),
        ),
    ]
