# Generated by Django 4.2.23 on 2025-08-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0127_new_changelog'),
        ('ipam', '0052_alter_ipaddress_index_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VRFObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ipam_vrfchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='ipam.vrf')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='VLANObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ipam_vlanchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='ipam.vlan')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='VLANGroupObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ipam_vlangroupchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='ipam.vlangroup')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='ServiceObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ipam_servicechangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='ipam.service')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='RouteTargetObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ipam_routetargetchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='ipam.routetarget')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='RIRObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ipam_rirchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='ipam.rir')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='PrefixObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ipam_prefixchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='ipam.prefix')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='NamespaceObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ipam_namespacechangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='ipam.namespace')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='IPAddressObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='ipam_ipaddresschangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='ipam.ipaddress')),
            ],
            bases=('extras.objectchange',),
        ),
    ]
