# Generated by Django 4.2.23 on 2025-08-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0054_changelog_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddressobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='namespaceobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='prefixobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='rirobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='routetargetobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='serviceobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='vlangroupobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='vlanobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='vrfobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
    ]
