# Generated by Django 4.2.23 on 2025-08-20 15:10

from django.db import migrations, models
import django.db.models.deletion

from nautobot.extras.migrations.helpers.new_objectchange import make_funcs_for_model


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0127_webhookobjectchange_teamobjectchange_tagobjectchange_and_more'),
        ('virtualization', '0030_alter_virtualmachine_local_config_context_data_owner_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMInterfaceObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='virtualization_vminterfacechangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='virtualization.vminterface')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='VirtualMachineObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='virtualization_virtualmachinechangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='virtualization.virtualmachine')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='ClusterTypeObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='virtualization_clustertypechangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='virtualization.clustertype')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='ClusterObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='virtualization_clusterchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='virtualization.cluster')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='ClusterGroupObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='virtualization_clustergroupchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='virtualization.clustergroup')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.RunPython(*make_funcs_for_model('virtualization', 'VMInterface')),
        migrations.RunPython(*make_funcs_for_model('virtualization', 'VirtualMachine')),
        migrations.RunPython(*make_funcs_for_model('virtualization', 'ClusterType')),
        migrations.RunPython(*make_funcs_for_model('virtualization', 'Cluster')),
        migrations.RunPython(*make_funcs_for_model('virtualization', 'ClusterGroup')),
    ]
