# Generated by Django 4.2.23 on 2025-08-20 15:10

from django.db import migrations

from nautobot.extras.migrations.helpers.new_objectchange import make_funcs_for_model


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0031_new_changelog'),
    ]

    operations = [
        migrations.RunPython(*make_funcs_for_model('virtualization', 'VMInterface')),
        migrations.RunPython(*make_funcs_for_model('virtualization', 'VirtualMachine')),
        migrations.RunPython(*make_funcs_for_model('virtualization', 'ClusterType')),
        migrations.RunPython(*make_funcs_for_model('virtualization', 'Cluster')),
        migrations.RunPython(*make_funcs_for_model('virtualization', 'ClusterGroup')),
    ]
