# Generated by Django 4.2.23 on 2025-08-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0032_changelog_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clustergroupobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='clusterobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='clustertypeobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='virtualmachineobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='vminterfaceobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
    ]
