# Generated by Django 4.2.23 on 2025-08-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0127_webhookobjectchange_teamobjectchange_tagobjectchange_and_more'),
        ('example_app', '0007_update_all_charfields_max_length_to_255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModelObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='example_app_examplemodelchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='example_app.examplemodel')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='AnotherExampleModelObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='example_app_anotherexamplemodelchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='example_app.anotherexamplemodel')),
            ],
            bases=('extras.objectchange',),
        ),
    ]
