# Generated by Django 4.2.23 on 2025-08-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0127_new_changelog"),
        ("wireless", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WirelessNetworkObjectChange",
            fields=[
                (
                    "changelog_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="wireless_wirelessnetworkchangelog",
                        serialize=False,
                        to="extras.objectchange",
                    ),
                ),
                ("target_uuid", models.UUIDField()),
                (
                    "fktarget",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="wireless.wirelessnetwork",
                    ),
                ),
            ],
            bases=("extras.objectchange",),
        ),
        migrations.CreateModel(
            name="SupportedDataRateObjectChange",
            fields=[
                (
                    "changelog_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="wireless_supporteddataratechangelog",
                        serialize=False,
                        to="extras.objectchange",
                    ),
                ),
                ("target_uuid", models.UUIDField()),
                (
                    "fktarget",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="wireless.supporteddatarate",
                    ),
                ),
            ],
            bases=("extras.objectchange",),
        ),
        migrations.CreateModel(
            name="RadioProfileObjectChange",
            fields=[
                (
                    "changelog_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="wireless_radioprofilechangelog",
                        serialize=False,
                        to="extras.objectchange",
                    ),
                ),
                ("target_uuid", models.UUIDField()),
                (
                    "fktarget",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="wireless.radioprofile",
                    ),
                ),
            ],
            bases=("extras.objectchange",),
        ),
    ]
