# Generated by Django 4.2.23 on 2025-08-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireless', '0003_changelog_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radioprofileobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='supporteddatarateobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='wirelessnetworkobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
    ]
