# Generated by Django 4.2.23 on 2025-08-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0125_jobresult_date_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectchange',
            name='target_model_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
