# Generated by Django 4.2.23 on 2025-08-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0128_changelog_migration'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='objectchange',
            name='extras_objectchange_triple_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectchange',
            name='extras_objectchange_rtime_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectchange',
            name='changed_object_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectchange',
            name='user_changed_object_idx',
        ),
        migrations.RemoveIndex(
            model_name='objectchange',
            name='user_name_changed_object_idx',
        ),
        migrations.RenameIndex(
            model_name='objectchange',
            new_name='extras_objectchange_triple_idx',
            old_name='extras_objectchange_double_idx',
        ),
        migrations.AlterUniqueTogether(
            name='objectchange',
            unique_together={('time', 'request_id', 'changed_object_type')},
        ),
        migrations.AddIndex(
            model_name='objectchange',
            index=models.Index(fields=['user', 'changed_object_type'], name='user_changed_object_typex'),
        ),
        migrations.RemoveField(
            model_name='objectchange',
            name='changed_object_id',
        ),
    ]
