# Generated by Django 4.2.23 on 2025-08-20 15:10

from django.db import migrations, models
import django.db.models.deletion

from nautobot.extras.migrations.helpers.new_objectchange import make_funcs_for_model


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0126_objectchange_target_model_name"),
        ("cloud", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudServiceObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cloud_cloudservicechangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='cloud.cloudservice')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='CloudResourceTypeObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cloud_cloudresourcetypechangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='cloud.cloudresourcetype')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='CloudNetworkObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cloud_cloudnetworkchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='cloud.cloudnetwork')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.CreateModel(
            name='CloudAccountObjectChange',
            fields=[
                ('changelog_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cloud_cloudaccountchangelog', serialize=False, to='extras.objectchange')),
                ('target_uuid', models.UUIDField()),
                ('fktarget', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='cloud.cloudaccount')),
            ],
            bases=('extras.objectchange',),
        ),
        migrations.RunPython(*make_funcs_for_model('cloud', 'CloudService')),
        migrations.RunPython(*make_funcs_for_model('cloud', 'CloudResourceType')),
        migrations.RunPython(*make_funcs_for_model('cloud', 'CloudNetwork')),
        migrations.RunPython(*make_funcs_for_model('cloud', 'CloudAccount')),
    ]
