# Generated by Django 4.2.23 on 2025-06-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cloudnetwork",
            constraint=models.CheckConstraint(
                check=models.Q(("parent", models.F("id")), _negated=True),
                name="cloud_network_no_self_parent",
                violation_error_message="A CloudNetwork may not be its own parent",
            ),
        ),
    ]
