# Generated by Django 4.2.16 on 2024-12-04 21:32

from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0001_initial"),
        ("cloud", "0002_optimization_initial_step_1"),
        ("dcim", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudservice",
            name="tags",
            field=nautobot.core.models.fields.TagsField(
                through="extras.TaggedItem", to="extras.Tag"
            ),
        ),
        migrations.AddField(
            model_name="cloudresourcetype",
            name="content_types",
            field=models.ManyToManyField(
                limit_choices_to=nautobot.extras.utils.FeatureQuery(
                    "cloud_resource_types"
                ),
                related_name="cloud_resource_types",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="cloudresourcetype",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cloud_resource_types",
                to="dcim.manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="cloudresourcetype",
            name="tags",
            field=nautobot.core.models.fields.TagsField(
                through="extras.TaggedItem", to="extras.Tag"
            ),
        ),
        migrations.AddField(
            model_name="cloudnetworkprefixassignment",
            name="cloud_network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prefix_assignments",
                to="cloud.cloudnetwork",
            ),
        ),
    ]
