# Generated by Django 4.2.16 on 2024-12-04 21:32

from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cloud", "0003_optimization_initial_step_2"),
        ("ipam", "0001_initial"),
        ("extras", "0117_optimization_initial_part_1"),
        ("dcim", "0064_optimization_initial_part_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudnetworkprefixassignment",
            name="prefix",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cloud_network_assignments",
                to="ipam.prefix",
            ),
        ),
        migrations.AddField(
            model_name="cloudnetwork",
            name="cloud_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cloud_networks",
                to="cloud.cloudaccount",
            ),
        ),
        migrations.AddField(
            model_name="cloudnetwork",
            name="cloud_resource_type",
            field=nautobot.core.models.fields.ForeignKeyLimitedByContentTypes(
                on_delete=django.db.models.deletion.PROTECT,
                to="cloud.cloudresourcetype",
            ),
        ),
        migrations.AddField(
            model_name="cloudnetwork",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="cloud.cloudnetwork",
            ),
        ),
        migrations.AddField(
            model_name="cloudnetwork",
            name="prefixes",
            field=models.ManyToManyField(
                blank=True,
                related_name="cloud_networks",
                through="cloud.CloudNetworkPrefixAssignment",
                to="ipam.prefix",
            ),
        ),
        migrations.AddField(
            model_name="cloudnetwork",
            name="tags",
            field=nautobot.core.models.fields.TagsField(
                through="extras.TaggedItem", to="extras.Tag"
            ),
        ),
        migrations.AddField(
            model_name="cloudaccount",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cloud_accounts",
                to="dcim.manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="cloudaccount",
            name="secrets_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="extras.secretsgroup",
            ),
        ),
        migrations.AddField(
            model_name="cloudaccount",
            name="tags",
            field=nautobot.core.models.fields.TagsField(
                through="extras.TaggedItem", to="extras.Tag"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cloudservicenetworkassignment",
            unique_together={("cloud_network", "cloud_service")},
        ),
        migrations.AlterUniqueTogether(
            name="cloudnetworkprefixassignment",
            unique_together={("cloud_network", "prefix")},
        ),
    ]
