# Generated by Django 4.2.23 on 2025-08-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_changelog_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudaccountobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='cloudnetworkobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='cloudresourcetypeobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
        migrations.RenameField(
            model_name='cloudserviceobjectchange',
            old_name='fktarget',
            new_name='changed_object',
        ),
    ]
