# Generated by Django 4.2.23 on 2025-08-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0127_new_changelog"),
        ("tenancy", "0009_update_all_charfields_max_length_to_255"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantObjectChange",
            fields=[
                (
                    "changelog_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="tenancy_tenantchangelog",
                        serialize=False,
                        to="extras.objectchange",
                    ),
                ),
                ("target_uuid", models.UUIDField()),
                (
                    "fktarget",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            bases=("extras.objectchange",),
        ),
        migrations.CreateModel(
            name="TenantGroupObjectChange",
            fields=[
                (
                    "changelog_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="tenancy_tenantgroupchangelog",
                        serialize=False,
                        to="extras.objectchange",
                    ),
                ),
                ("target_uuid", models.UUIDField()),
                (
                    "fktarget",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="tenancy.tenantgroup",
                    ),
                ),
            ],
            bases=("extras.objectchange",),
        ),
    ]
