# Generated by Django 4.2.23 on 2025-08-20 15:10

from django.db import migrations

from nautobot.extras.migrations.helpers.new_objectchange import make_funcs_for_model


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_new_changelog'),
    ]

    operations = [
        migrations.RunPython(*make_funcs_for_model('tenancy', 'Tenant')),
        migrations.RunPython(*make_funcs_for_model('tenancy', 'TenantGroup')),
    ]
